# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.vdm.rss:
        class: AppBundle\Service\VdmRss
        arguments:
            - '%vdm.rss.url%'
            - '@feedio'
            - '@doctrine.orm.entity_manager'
            - '@logger'